[package]
name = "rust_linesweeper"
version = "0.1.0"
authors = ["Jakob Lindqvist <jakob.lindqvist@2050engineering.se>"]
edition = "2018"

[dependencies]
serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.82"
